name: "Build"

on:
  workflow_dispatch:
  # Do not build on push to master
  # push:
  #   branches:
  #     - master

  # Do not build on internal pull requests
  # pull_request:

  # Do not allow to trigger for external PRs
  # workflow_dispatch:

  # Also run regularly because pushes initiated by GitHub Actions don't
  # trigger the above events.
  schedule:
    # every day at 8:10 UTC
    - cron: "10 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v14
        with:
          name: foldu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush: "result-eunzip"
      - run: |
          nix build .#eunzip -o result-eunzip
